name: Norminette

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  check-norminette:
    name: Norminette Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Norminette
        uses: 42School/norminette@v3.3.51
        with:
          args: '-R CheckForbiddenSourceHeader'
